Remove various warnings with Elixir 1.4.  Change deprecated Float.to_string to
mykewould/crutches pull request #111
Opened 2017-01-12 19:13 UTC by udfalkso

After upgrading to Elixir 1.4 I was seeing lots of warnings in the development log.  This pull request removes all of them, with all tests still passing.  

Thanks for the lib!

```
warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  mix.exs:10

Compiling 2 files (.ex)
warning: unused import String.capitalize/1
  lib/crutches/string.ex:3

warning: unused import String.downcase/1
  lib/crutches/string.ex:3

warning: unused import String.split/2
  lib/crutches/string.ex:3

warning: the variable "fract_num" is unsafe as it has been set inside a case/cond/receive/if/&&/||. Please explicitly return the variable value instead. For example:

    case int do
      1 -> atom = :one
      2 -> atom = :two
    end

should be written as

    atom =
      case int do
        1 -> :one
        2 -> :two
      end

Unsafe variable found at:
  lib/crutches/format/number.ex:712

.................................................................................................warning: Mix.Utils.camelize/1 is deprecated, use Macro.camelize/1 instead
  (mix) lib/mix/utils.ex:250: Mix.Utils.camelize/1
  (for doctest at) lib/crutches/string.ex:60: Crutches.StringTest."test doc at Crutches.String.camelize/1 (4)"/1
  (ex_unit) lib/ex_unit/runner.ex:302: ExUnit.Runner.exec_test/1
  (stdlib) timer.erl:166: :timer.tc/1
  (ex_unit) lib/ex_unit/runner.ex:250: anonymous fn/3 in ExUnit.Runner.spawn_test/3

....warning: Mix.Utils.camelize/1 is deprecated, use Macro.camelize/1 instead
  (mix) lib/mix/utils.ex:250: Mix.Utils.camelize/1
  (for doctest at) lib/crutches/string.ex:51: Crutches.StringTest."test doc at Crutches.String.camelize/1 (1)"/1
  (ex_unit) lib/ex_unit/runner.ex:302: ExUnit.Runner.exec_test/1
  (stdlib) timer.erl:166: :timer.tc/1
  (ex_unit) lib/ex_unit/runner.ex:250: anonymous fn/3 in ExUnit.Runner.spawn_test/3

..warning: Mix.Utils.underscore/1 is deprecated, use Macro.underscore/1 instead
  (mix) lib/mix/utils.ex:244: Mix.Utils.underscore/1
  (for doctest at) lib/crutches/string.ex:27: Crutches.StringTest."test doc at Crutches.String.underscore/1 (29)"/1
  (ex_unit) lib/ex_unit/runner.ex:302: ExUnit.Runner.exec_test/1
  (stdlib) timer.erl:166: :timer.tc/1
  (ex_unit) lib/ex_unit/runner.ex:250: anonymous fn/3 in ExUnit.Runner.spawn_test/3

..warning: Mix.Utils.camelize/1 is deprecated, use Macro.camelize/1 instead
  (mix) lib/mix/utils.ex:250: Mix.Utils.camelize/1
  (for doctest at) lib/crutches/string.ex:57: Crutches.StringTest."test doc at Crutches.String.camelize/1 (3)"/1
  (ex_unit) lib/ex_unit/runner.ex:302: ExUnit.Runner.exec_test/1
  (stdlib) timer.erl:166: :timer.tc/1
  (ex_unit) lib/ex_unit/runner.ex:250: anonymous fn/3 in ExUnit.Runner.spawn_test/3

......warning: Mix.Utils.underscore/1 is deprecated, use Macro.underscore/1 instead
  (mix) lib/mix/utils.ex:244: Mix.Utils.underscore/1
  (for doctest at) lib/crutches/string.ex:36: Crutches.StringTest."test doc at Crutches.String.underscore/1 (32)"/1
  (ex_unit) lib/ex_unit/runner.ex:302: ExUnit.Runner.exec_test/1
  (stdlib) timer.erl:166: :timer.tc/1
  (ex_unit) lib/ex_unit/runner.ex:250: anonymous fn/3 in ExUnit.Runner.spawn_test/3

.warning: Mix.Utils.underscore/1 is deprecated, use Macro.underscore/1 instead
  (mix) lib/mix/utils.ex:244: Mix.Utils.underscore/1
  (for doctest at) lib/crutches/string.ex:30: Crutches.StringTest."test doc at Crutches.String.underscore/1 (30)"/1
  (ex_unit) lib/ex_unit/runner.ex:302: ExUnit.Runner.exec_test/1
  (stdlib) timer.erl:166: :timer.tc/1
  (ex_unit) lib/ex_unit/runner.ex:250: anonymous fn/3 in ExUnit.Runner.spawn_test/3

..warning: Mix.Utils.underscore/1 is deprecated, use Macro.underscore/1 instead
  (mix) lib/mix/utils.ex:244: Mix.Utils.underscore/1
  (for doctest at) lib/crutches/string.ex:33: Crutches.StringTest."test doc at Crutches.String.underscore/1 (31)"/1
  (ex_unit) lib/ex_unit/runner.ex:302: ExUnit.Runner.exec_test/1
  (stdlib) timer.erl:166: :timer.tc/1
  (ex_unit) lib/ex_unit/runner.ex:250: anonymous fn/3 in ExUnit.Runner.spawn_test/3

........warning: Mix.Utils.camelize/1 is deprecated, use Macro.camelize/1 instead
  (mix) lib/mix/utils.ex:250: Mix.Utils.camelize/1
  (for doctest at) lib/crutches/string.ex:54: Crutches.StringTest."test doc at Crutches.String.camelize/1 (2)"/1
  (ex_unit) lib/ex_unit/runner.ex:302: ExUnit.Runner.exec_test/1
  (stdlib) timer.erl:166: :timer.tc/1
  (ex_unit) lib/ex_unit/runner.ex:250: anonymous fn/3 in ExUnit.Runner.spawn_test/3

.warning: Mix.Utils.underscore/1 is deprecated, use Macro.underscore/1 instead
  (mix) lib/mix/utils.ex:244: Mix.Utils.underscore/1
  test/crutches/string_test.exs:8: anonymous fn/1 in Crutches.StringTest.compare_underscored_camel/1
  (elixir) lib/enum.ex:645: Enum."-each/2-lists^foreach/1-0-"/2
  (elixir) lib/enum.ex:645: Enum.each/2
  test/crutches/string_test.exs:29: Crutches.StringTest."test camel_with_module_to_underscore_with_slash"/1

warning: Mix.Utils.underscore/1 is deprecated, use Macro.underscore/1 instead
  (mix) lib/mix/utils.ex:244: Mix.Utils.underscore/1
  test/crutches/string_test.exs:8: anonymous fn/1 in Crutches.StringTest.compare_underscored_camel/1
  (elixir) lib/enum.ex:645: Enum."-each/2-lists^foreach/1-0-"/2
  (elixir) lib/enum.ex:645: Enum.each/2
  test/crutches/string_test.exs:29: Crutches.StringTest."test camel_with_module_to_underscore_with_slash"/1

warning: Mix.Utils.underscore/1 is deprecated, use Macro.underscore/1 instead
  (mix) lib/mix/utils.ex:244: Mix.Utils.underscore/1
  test/crutches/string_test.exs:8: anonymous fn/1 in Crutches.StringTest.compare_underscored_camel/1
  (elixir) lib/enum.ex:645: Enum."-each/2-lists^foreach/1-0-"/2
  (elixir) lib/enum.ex:645: Enum.each/2
  test/crutches/string_test.exs:29: Crutches.StringTest."test camel_with_module_to_underscore_with_slash"/1

..warning: Mix.Utils.underscore/1 is deprecated, use Macro.underscore/1 instead
  (mix) lib/mix/utils.ex:244: Mix.Utils.underscore/1
  test/crutches/string_test.exs:8: anonymous fn/1 in Crutches.StringTest.compare_underscored_camel/1
  (elixir) lib/enum.ex:645: Enum."-each/2-lists^foreach/1-0-"/2
  (elixir) lib/enum.ex:645: Enum.each/2
  test/crutches/string_test.exs:20: Crutches.StringTest."test camel_to_underscore_without_reverse"/1

warning: Mix.Utils.underscore/1 is deprecated, use Macro.underscore/1 instead
  (mix) lib/mix/utils.ex:244: Mix.Utils.underscore/1
  test/crutches/string_test.exs:8: anonymous fn/1 in Crutches.StringTest.compare_underscored_camel/1
  (elixir) lib/enum.ex:645: Enum."-each/2-lists^foreach/1-0-"/2
  (elixir) lib/enum.ex:645: Enum.each/2
  test/crutches/string_test.exs:20: Crutches.StringTest."test camel_to_underscore_without_reverse"/1

warning: Mix.Utils.underscore/1 is deprecated, use Macro.underscore/1 instead
  (mix) lib/mix/utils.ex:244: Mix.Utils.underscore/1
  test/crutches/string_test.exs:8: anonymous fn/1 in Crutches.StringTest.compare_underscored_camel/1
  (elixir) lib/enum.ex:645: Enum."-each/2-lists^foreach/1-0-"/2
  (elixir) lib/enum.ex:645: Enum.each/2
  test/crutches/string_test.exs:20: Crutches.StringTest."test camel_to_underscore_without_reverse"/1

warning: Mix.Utils.underscore/1 is deprecated, use Macro.underscore/1 instead
  (mix) lib/mix/utils.ex:244: Mix.Utils.underscore/1
  test/crutches/string_test.exs:8: anonymous fn/1 in Crutches.StringTest.compare_underscored_camel/1
  (elixir) lib/enum.ex:645: Enum."-each/2-lists^foreach/1-0-"/2
  (elixir) lib/enum.ex:645: Enum.each/2
  test/crutches/string_test.exs:20: Crutches.StringTest."test camel_to_underscore_without_reverse"/1

warning: Mix.Utils.underscore/1 is deprecated, use Macro.underscore/1 instead
  (mix) lib/mix/utils.ex:244: Mix.Utils.underscore/1
  test/crutches/string_test.exs:8: anonymous fn/1 in Crutches.StringTest.compare_underscored_camel/1
  (elixir) lib/enum.ex:645: Enum."-each/2-lists^foreach/1-0-"/2
  (elixir) lib/enum.ex:645: Enum.each/2
  test/crutches/string_test.exs:2 [...]

2017-01-12 21:47 UTC, duijf requested changes
Thanks very much for the PR! I've added a few minor comments

I've pushed a commit to master that runs the CI checks for Elixir 1.3 and 1.4. Can you rebase your branch off master to include the commit and push again? That way, we can run your changes on Travis for those Elixir versions as well

2017-01-12 21:47 UTC, duijf commented on lib/crutches/format/number.ex
> +      "111.234"
There have been changes to `Float.ceil/2`, `Float.floor/2` and `Float.round/2` in Elixir 1.4. The test-case covered the old behaviour. I'd rather not break backwards compatibility here: the old result is probably what users would expect (but any input regarding this is welcome!)

I think it is best if we remove this change and consider this as a bug on 1.4

2017-01-12 21:47 UTC, duijf commented on lib/crutches/string.ex
> +  defdelegate underscore(string), to: Macro
We can probably just get rid of these delegates and tests (and cut a new release), since they're not really adding anything compared to the stdlib

2017-01-13 19:24 UTC, udfalkso commented on lib/crutches/format/number.ex
> +      "111.234"
Yeah I thought about this one a bit before changing it.  Python agrees with 1.4, ruby agrees with 1.3.  I'll change the test back.

2017-01-13 19:55 UTC, udfalkso commented
Rebased and reverted the round() test, which now fails again.

2017-01-13 19:55 UTC, udfalkso commented on lib/crutches/string.ex
> +  defdelegate underscore(string), to: Macro
I suppose I'll leave this to you guys.

2017-01-15 20:58 UTC, duijf approved these changes

2017-01-15 20:59 UTC, merged

2017-01-15 21:00 UTC, duijf commented
Thank you very much! :)