Fix as_rounded to produce decimal accurate results
mykewould/crutches pull request #115
Opened 2017-02-24 17:15 UTC by carlism

Using a bit of a hack to avoid needing a decimal module dependency

2017-02-25 21:08 UTC, duijf requested changes
Hi @carlism! Thanks a lot for the PR :) 

I must admit I have no idea how this works exactly. Could you elaborate on your changes? I've also added a comment about style

2017-02-25 21:08 UTC, duijf commented on lib/crutches/format/number.ex
> +    number = number |> Kernel.*(multiplier) |> Float.round(0) |> Kernel./(multiplier)
I think the pipe operator makes this less readable. Can you change this line to:

```elixir
number = Float.round(multiplier * number, 0) / multiplier
```

2017-02-26 04:06 UTC, carlism commented
Requested change made.  Thanks for the feedback.  And as for how it works, I noticed all the examples that round up to a whole number do it exactly as you'd expect.  So I simply shifted the decimal before the call to round so it was rounding to a whole number then shifted it back.  The alternative is to pull in a Decimal math dependency and do the rounding with decimal precision as opposed to floating point math.

2017-02-26 08:50 UTC, duijf approved these changes

2017-02-26 08:51 UTC, merged

2017-02-26 08:52 UTC, duijf commented
Thanks for the explanation and for the contribution! :smile: